## Note, "[ci skio]" or "[skip ci]" within a commit message _should_
##  cause Travis Continuous Integration to skip the following

## Clone settings for repository
git:
  branch: master
  # depth: 3


## List of Operating Systems to test on
dist: xenial
os:
  - linux


## Attempt to limit environment to only what is required
language: bash
matrix:
  include:
    - bash


branches:
  only:
    - master
  except:
    - gh-pages


## Do the things
before_install:
  - sudo apt-get install -y unbound nginx git-core
  - mkdir -vp "/tmp/ssh_test_keys"
  - ssh-keygen -t ecdsa -f "/tmp/ssh_test_keys/bill" -C '' -N ''
  - ssh-keygen -t ecdsa -f "/tmp/ssh_test_keys/ted" -C '' -N ''

install:
  - chmod +x Makefile
  - sudo make install-dependencies
  - sudo make install

before_script:
  - if [ -e "$(which jekyll_usermod.sh)" ]; then echo 'Cannont locate installed jekyll_usermod.sh'; exit 1; fi
  - if [ -e "$(which jekyll_dnsconf.sh)" ]; then echo 'Cannont locate installed jekyll_dnsconf.sh'; exit 1; fi
  - if [ -e "$(which jekyll_wwwconf.sh)" ]; then echo 'Cannont locate installed jekyll_wwwconf.sh'; exit 1; fi

script:
  - jekyll_usermod.sh --user "Bill" --group "devs" --ssh-auth-keys "/tmp/ssh_test_keys/bill"
  - jekyll_usermod.sh --user "Ted" --group "devs" --ssh-auth-keys "'$(<"/tmp/ssh_test_keys/ted")'"
  - jekyll_dnsconf.sh --domain "devs" --tld "lan"
  - ssh Bill@localhost -i /tmp/ssh_test_keys/bill jekyll-build Bill
  - ssh Ted@localhost -i /tmp/ssh_test_keys/ted jekyll-build Ted
  - jekyll_wwwconf.sh --user "Bill" --domain "devs" --tld "lan" --repo "Bill"
  - jekyll_wwwconf.sh --user "Ted" --domain "devs" --tld "lan" --repo "Ted"

# install:
#   - chmod +x .travis-ci/install.sh
#   - .travis-ci/install.sh
#
# script:
#   - chmod +x .travis-ci/script.sh
#   - .travis-ci/script.sh
#
# after_success:
#   - chmod +x .travis-ci/after_success.sh
#   - .travis-ci/after_success.sh
#
# after_failure:
#   - chmod +x .travis-ci/after_failure.sh
#   - .travis-ci/after_failure.sh
#
# before_deploy:
#   - chmod +x .travis-ci/before_deploy.sh
#   - .travis-ci/before_deploy.sh
#
# deploy:
#   - chmod +x .travis-ci/deploy.sh
#   - .travis-ci/deploy.sh
#
# after_deploy:
#   - chmod +x .travis-ci/after_deploy.sh
#   - .travis-ci/after_deploy.sh
#
# after_script:
#   - chmod +x .travis-ci/after_script.sh
#   - .travis-ci/after_script.sh
