## Note, "[ci skio]" or "[skip ci]" within a commit message _should_
##  cause Travis Continuous Integration to skip the following

## Clone settings for repository
git:
  depth: 10
  quite: true
  submodules: false


## List of Operating Systems to test on
# dist: xenial
# ## ^^ Default was trusty as of 2019
# os:
#   - linux


## Attempt to limit environment to only what is required
language: bash
matrix:
  fast_finish: true
  ## Thanks be to, https://docs.travis-ci.com/user/multi-os/
  include:
    ## Default as of 2019
    - os: linux
      dist: trusty
    ## Suggested in Travis CI blog
    - os: linux
      dist: xenial


branches:
  only:
    - master
  except:
    - gh-pages


## Note, caching may make following builds a little faster
## To-do, test 'make update' through the use of caching
# cache:
#   directories:
#     - /home/travis/.ssh


## Do the things
before_install:
  - sudo apt-get install -yqq unbound nginx git-core ruby-full build-essential zlib1g-dev
  - mkdir -vp "/home/travis/.ssh"
  - ssh-keygen -q -t ecdsa -f "/home/travis/.ssh/bill" -C '' -N ''

install:
  - chmod +x Makefile
  - sudo make install-dependencies
  - sudo make install

before_script:
  - if ! [ -L "$(which jekyll_usermod.sh)" ]; then echo 'BUG usermod' && false; fi
  - if ! [ -L "$(which jekyll_dnsconf.sh)" ]; then echo 'BUG dnsconf' && false; fi
  - if ! [ -L "$(which jekyll_wwwconf.sh)" ]; then echo 'BUG wwcwonf' && false; fi

script:
  - sudo jekyll_usermod.sh --user "Bill" --group "devs" --ssh-auth-keys "/home/travis/.ssh/bill.pub"
  - sudo jekyll_dnsconf.sh --domain "devs" --tld "lan"
  - sudo cat "/etc/unbound/unbound.conf.d/devs.lan.conf"
  ## Note Travis does not take kindly to StrictHostKeyChecking=accept-new
  - ssh Bill@localhost -o 'StrictHostKeyChecking no' -i "/home/travis/.ssh/bill" list --license

  - ssh Bill@localhost -i "/home/travis/.ssh/bill" list .
  - ssh Bill@localhost -i "/home/travis/.ssh/bill" git-init Ideas
  - ssh Bill@localhost -i "/home/travis/.ssh/bill" list git

  ## To-do, sort-out gem install bundler on Travis CI VMs
  # - ssh Bill@localhost -i "/home/travis/.ssh/bill" bundle-install Bill
  # - ssh Bill@localhost -i "/home/travis/.ssh/bill" jekyll-build Bill
  # - ssh Bill@localhost -i "/home/travis/.ssh/bill" list www
  # - sudo ls -hal /srv/bill/www
  # - sudo jekyll_wwwconf.sh --user "Bill" --domain "devs" --tld "lan" --repo "Bill"
  # - cat "/etc/nginx/sites-enabled/bill.devs.lan"

after_failure:
  - printf 'after_failure asks - Where did %s go wrong?\n' "${USER}"

after_success:
  - echo 'after_success states - No errors, this time...'

after_script:
  - echo 'after_script is all good!'
