# Site settings
title: Jekyll Admin
description: >- # this means to ignore newlines until "baseurl:"
  Collection of Bash scripts for Jekyll and Git server administration.
  Unless otherwise stated both documentation and code are shared under
  the "GNU AGPL version 3" license by default.
url: "'https://s0ands0.github.io'" # Required for `absolute_url` Liquid piping
author: S0AndS0

# Build settings
markdown: kramdown
theme: minima
show_excerpts: true
plugins:
  - jekyll-feed


## Theme settings
minima:
  social_links:
    github: S0AndS0
    youtube_channel: UCmR4BGgzj_ZrrDIR0A0uSEg
    youtube_channel_name: Various Video Guides


## Thanks be to - https://stackoverflow.com/a/45870924/2632107
##  for the following sweat bits
sass:
  load_paths:
    - _sass
    - _scss


## Thanks be to - https://jekyllrb.com/docs/collections/
collections:
  administration:
    output: true
    layout: post
  git_shell_commands:
    output: true
    layout: post
  licensing:
    output: true
    layout: default


## Exclude from processing; by default commented items will not be processed.
exclude:
  - README.md
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
